### ISSUE TITLE
Historia de usuario Evaluar un bootcamp - propuesta

### ISSUE THREAD

**Issue by jaimecuellar** [Trycatch-tv/ValidadorBootcamp#13]
Me surgen algunas dudas ¿quién evalúa los bootcamps? ¿cómo es el procedimiento para hacerlo?
He revisado las historias de usuario y no lo veo claramente. Por eso propongo esta historia de usuario:

## Evaluar un bootcamp
* **Nombre del usuario:** Evaluador/Experto, Administrador
* **Objetivo:** Evaluar un bootcamp según criterios establecidos
* **Flujo principal:**
    * El usuario visita la página de inicio del validador de bootcamps.
    * El usuario selecciona la pestaña "Lista de bootcamps".
    * El usuario ve una lista de bootcamps, organizados por tema, precio, duración, etc.
    * El usuario selecciona la pestaña "Reviews del bootcamp".
    * El usuario se dirige a un bootcamp "sin calificaciones", verificado pero sin calificaciones.
    * El usuario da click en "Evaluar".
    * El usuario pasa por cada una de las categorías y da su puntaje.
    * El usuario da click en "Enviar evaluación".

**Comment by Orliluq** [comment]
[Proceso para evaluar un bootcamp.pdf](https://github.com/Trycatch-tv/ValidadorBootcamp/files/13553555/Proceso.para.evaluar.un.bootcamp.pdf)
Basándome en esta propuesta investigué sobre ésta historia de usuario y aquí remito una síntesis del tema, espero sirva de algo.

**Comment by jaimecuellar** [comment]
Sirve, sirve! En la Wiki ya hay un apartado para los avances. Por ahora sólo puse categorías y variables candidatas:
[Ficha metodológica: Criterios y Construcción de Índice de Evaluación de Bootcamps](https://github.com/Trycatch-tv/ValidadorBootcamp/wiki/Ficha-metodol%C3%B3gica:-Criterios-y-Construcci%C3%B3n-de-%C3%8Dndice-de-Evaluaci%C3%B3n-de-Bootcamps)
Voy a poner el texto que sugieres allá (si no te parece, me avisas y lo revierto).

**Comment by jaimecuellar** [comment]
La historia de usuario ya fue agregada a la Wiki principal: [Historias de Usuario](https://github.com/Trycatch-tv/ValidadorBootcamp/wiki/Historias-de-Usuario)
