### ISSUE TITLE
UI - Crear mockup en Figma

### ISSUE THREAD

**Issue by judlup** [Trycatch-tv/ValidadorBootcamp#5]
## Descripción

- Crear el diseño de Figma del proyecto basado en el mockup que tenemos y el sitio desplegado en el [demo en dev](https://dev-validador-bootcamps.netlify.app/)

![Image](https://github.com/Trycatch-tv/ValidadorBootcamp/assets/3951903/7c0a890a-b806-425b-a50c-462853fd7576)

## Criterios de aceptación

- Link del proyecto con los alcances definidos en el mockup diagramados y organizados dentro del archivo Figma

**Comment by gguanaco** [comment]
On it! 🐱‍👤
